language: php
os: linux
dist: bionic

addons:
  apt:
    packages:
      # Needed for media library (uses intervention image for conversion)
      - php7.4-gd

php:
  - 7.4

before_install:
  - sudo wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo apt-get -y install php7.4-gd

install:
  - rm .env.example
  - cp .env.travis .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - touch ./database/database.sqlite
  - php artisan key:generate
  - php artisan migrate --database=sqlite --no-interaction
  - travis_retry composer self-update

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml --verbose

after_success:
  - bash <(curl -s https://codecov.io/bash)
