language: php
os: linux
dist: bionic

php:
  - 7.4

services:
  - redis-server

before_install:
  - phpenv config-rm xdebug.ini
  - sudo wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - yes | pecl install imagick
  - sudo sed -i -e 's/rights="none" pattern="PDF"/rights="read|write" pattern="PDF"/' /etc/ImageMagick-6/policy.xml
  - wget https://salimdj.me/nova.zip
  - unzip nova.zip
  - wget https://salimdj.me/data.zip
  - unzip data.zip

install:
  - rm .env.example
  - cp .env.travis .env
  - touch ./database/database.sqlite
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - php artisan key:generate
  - php artisan migrate --database=sqlite --no-interaction
  - travis_retry composer self-update

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml --verbose

after_success:
  - bash <(curl -s https://codecov.io/bash)
